name: Module

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # VPC Module
      - name: Init and Apply VPC Module
        working-directory: modules/vpc
        run: |
          terraform init \
            -backend-config="bucket=powertool19087" \
            -backend-config="key=vpc/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=powertool" \
            -reconfigure
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

      # Security Group Module
      - name: Init and Apply Security Group Module
        working-directory: modules/security_group
        run: |
          terraform init \
            -backend-config="bucket=powertool19087" \
            -backend-config="key=security_group/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=powertool" \
            -reconfigure
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

      # Subnet Module
      - name: Init and Apply Subnet Module
        working-directory: modules/subnet
        run: |
          terraform init \
            -backend-config="bucket=powertool19087" \
            -backend-config="key=subnet/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=powertool" \
            -reconfigure
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
