name: Module

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # VPC Module
      - name: Init & Apply VPC Module
        working-directory: modules/vpc
        run: |
          terraform init \
            -backend-config="bucket=powertool19087" \
            -backend-config="key=vpc/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=powertool" \
            -reconfigure

          terraform plan \
            -var="vpc_name=dev-vpc" \
            -var="cidr_block=10.0.0.0/16" \
            -out=tfplan

          terraform apply -auto-approve tfplan

      # Security Group Module
      - name: Init & Apply Security Group Module
        working-directory: modules/security_group
        run: |
          terraform init \
            -backend-config="bucket=powertool19087" \
            -backend-config="key=security_group/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=powertool" \
            -reconfigure

          terraform plan \
            -var="security_group_name=web-sg" \
            -var="vpc_id=vpc-12345678" \
            -out=tfplan

          terraform apply -auto-approve tfplan

      # Subnet Module
      - name: Init & Apply Subnet Module
        working-directory: modules/subnet
        run: |
          terraform init \
            -backend-config="bucket=powertool19087" \
            -backend-config="key=subnet/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=powertool" \
            -reconfigure

          terraform plan \
            -var="subnet_name=public-subnet" \
            -var="vpc_id=vpc-12345678" \
            -var="cidr_block=10.0.1.0/24" \
            -var="availability_zone=us-east-1a" \
            -out=tfplan

          terraform apply -auto-approve tfplan
